services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    image: denoland/deno:1.40.2
    container_name: deno_app
    working_dir: /app
    volumes:
      - ./src:/app
      - deno_cache_app:/deno-dir
    ports:
      - "3008:3000"
    depends_on:
      - postgres
    environment:
      DENO_DIR: /deno-dir
      DATABASE_URL: postgres://postgres:password@postgres:5432/myapp
      EXTERNAL_API_URL: http://mock-server:4000
    command: sh -c "sleep 2 && deno run --allow-net --allow-env --allow-read --allow-write --watch main.ts"
    networks:
      - app-network

  mock-server:
    image: denoland/deno:1.40.2
    container_name: mock_server
    working_dir: /app
    volumes:
      - ./mock-server:/app
      - deno_cache_mock:/deno-dir
    ports:
      - "4000:4000"
    environment:
      DENO_DIR: /deno-dir
    command: sh -c "sleep 1 && deno run --allow-net --allow-env --allow-read --allow-write --watch main.ts"
    networks:
      - app-network

volumes:
  postgres_data:
  deno_cache_app:
  deno_cache_mock:

networks:
  app-network:
    driver: bridge
